javascript:
  front:
    # filename to output
    root: "."
    filename: "script.js"
    notification: "Running JavaScript"
    bowerPaths:
      - "bower_components/foundation-sites/js/foundation.core.js"
      - "bower_components/foundation-sites/js/foundation.util.keyboard.js"
      - "bower_components/foundation-sites/js/foundation.util.box.js"
      - "bower_components/foundation-sites/js/foundation.util.nest.js"
      - "bower_components/foundation-sites/js/foundation.util.mediaQuery.js"
      - "bower_components/foundation-sites/js/foundation.util.triggers.js"
      - "bower_components/foundation-sites/js/foundation.util.motion.js"
      - "bower_components/foundation-sites/js/foundation.util.timerAndImageLoader.js"
      - "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
      - "bower_components/foundation-sites/js/foundation.offcanvas.js"
      - "bower_components/foundation-sites/js/foundation.sticky.js"
      - "bower_components/foundation-sites/js/foundation.magellan.js"
      - "bower_components/foundation-sites/js/foundation.equalizer.js"
    # Paths to JavaScript libraries, which are combined into one file
    src:
      # Paths to your own project code are here
      # All the files in this list and in the js dir are concatenated into script.js
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
  admin:
    root: "."
    filename: "admin.js"
    notification: "Running Admin JavaScript"
    src:
      - "build/js/admin/**/*.js"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  front:
    notification: "Running Sass"
    bowerPaths:
      - "bower_components/foundation-sites/scss"
      - "bower_components/motion-ui/src"
    root: "."
    src: "build/sass/main.scss"
  admin:
    notification: "Running Admin Sass"
    root: "."
    src: "build/sass/admin/main.scss"
  login:
    notification: "Running Login Sass"
    root: "."
    src: "build/sass/login/main.scss"

watch:
  javascript:
    front:
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
    admin: "build/js/admin/**/*.js"
  sass: 
    front: 
      - "build/sass/**/*.scss"
      - "!build/sass/admin/**/*.scss"
      - "!build/sass/login/**/*.scss"
    admin: "build/sass/admin/**/*.scss"
    login: "build/sass/login/**/*.scss"
