javascript:
  front:
    root: "."
    # filename to output
    filename: "script.js"
    vendor: 
      - "node_modules/foundation-sites/js/foundation.core.js"
      - "node_modules/foundation-sites/js/foundation.util.keyboard.js"
      - "node_modules/foundation-sites/js/foundation.util.box.js"
      - "node_modules/foundation-sites/js/foundation.util.nest.js"
      - "node_modules/foundation-sites/js/foundation.util.mediaQuery.js"
      - "node_modules/foundation-sites/js/foundation.util.triggers.js"
      - "node_modules/foundation-sites/js/foundation.util.motion.js"
      - "node_modules/foundation-sites/js/foundation.util.timerAndImageLoader.js"
      - "node_modules/foundation-sites/js/foundation.dropdownMenu.js"
      - "node_modules/foundation-sites/js/foundation.offcanvas.js"
      - "node_modules/foundation-sites/js/foundation.sticky.js"
      - "node_modules/foundation-sites/js/foundation.magellan.js"
      - "node_modules/foundation-sites/js/foundation.equalizer.js"
    notification: "Running JavaScript"
    # Paths to JavaScript libraries, which are combined into one file
    src:
      # Paths to your own project code are here
      # All the files in this list and in the js dir are concatenated into script.js
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
      - "!build/js/tinymce/**/*.js"
  admin:
    root: "."
    filename: "admin.js"
    vendor:
      - ""
    notification: "Running Admin JavaScript"
    src:
      - "build/js/admin/**/*.js"
  tinymce:
    root: "./assets/js/tinymce/"
    notification: "Running TinyMCE JavaScript"
    src:
      - "build/js/tinymce/**/*.js"

sass:
  # Autoprefixer will make sure your CSS works with these browsers
  compatibility:
    - "last 2 versions"
    - "ie >= 9"
  front:
    root: "."
    filename: "app.css"
    vendor: 
      - "node_modules/foundation-sites/scss"
      - "node_modules/motion-ui/src"
    notification: "Running Sass"
    src: "build/sass/main.scss"
  admin:
    root: "."
    filename: "admin.css"
    vendor:
      - ""
    notification: "Running Admin Sass"
    src: "build/sass/admin/main.scss"
  login:
    notification: "Running Login Sass"
    root: "."
    filename: "login.css"
    vendor:
      - ""
    src: "build/sass/login/main.scss"

watch:
  javascript:
    front:
      - "build/js/**/*.js"
      - "!build/js/admin/**/*.js"
      - "!build/js/tinymce/**/*.js"
    admin: "build/js/admin/**/*.js"
    tinymce: "build/js/tinymce/**/*.js"
  sass: 
    front: 
      - "build/sass/**/*.scss"
      - "!build/sass/admin/**/*.scss"
    admin: "build/sass/admin/**/*.scss"
    login: "build/sass/login/**/*.scss"

release:
  type: 'theme'
  languagesDir: './languages/'
  files:
    - "./**/*.*"
    - "!./**/*.map"
    - "!./**/build/**/*.*"
    - "!./**/.git/**"
    - "!./**/.gitignore"
    - "!./**/.gitmodules"
    - "!./**/gulpfile.js"
    - "!./**/gruntfile.js"
    - "!./**/gulp/**/*.*"
    - "!./**/package.json"
    - "!./**/package-lock.json"
    - "!./**/bower.json"
    - "!./**/composer.json"
    - "!./**/node_modules/**/*.*"
    - "!./**/bower_components/**/*.*"
    - "!./**/README.md"
    - "!./**/*.zip"